### ISSUE TITLE
not booting from SD card w/ uboot

### ISSUE THREAD

**Issue by nrpetonr** [BredOS/images#13]
SDcard install not booting on orangepi 5 plus, release 2024-10-04., u-boot. I have NVME ubuntu installed and it boots to this one even if SD with BREDos is inserted.

**Comment by doofin** [comment]
Any more details? Do u use dd to write the image? which img do u use?

**Comment by nrpetonr** [comment]
image for orangepi 5 plus, writing with balena etcher.  no problem when using build 2024-09-01.

**Comment by fydepanda** [comment]
@nrpetonr Do you have anything on the SPI

**Comment by fydepanda** [comment]
if you want to boot bredOS you need to setup ubuntu for UEFI and put UEFI on the SPI or just wipe the SPI

**Comment by nrpetonr** [comment]
i see, my assumption was correct then. by the way, don't u consider addidnt mailine kernel as an option toyour builds?

**Comment by fydepanda** [comment]
It depends on the device, currently there is no support for any opi device in mainline, if you look at the indiedroid nova we already have mainline images
