### ISSUE TITLE
error: key "1BEF1BCEBA58EA33" could not be looked up remotely

### ISSUE THREAD

**Issue by doofin** [BredOS/images#15]
I imported some keys ,but seems some are still missing when run mkimage : 

> Total Installed Size:  3768.77 MiB
> :: Proceed with installation? [Y/n] 
> (613/613) checking keys in keyring                 [#########################] 100%
> downloading required keys...
> :: Import PGP key 1BEF1BCEBA58EA33, "Bill Sideris <bill88t@feline.gr>"? [Y/n] 
> error: key "1BEF1BCEBA58EA33" could not be looked up remotely
> error: required key missing from keyring
> error: failed to commit transaction (unexpected error)
> Errors occurred, no packages were upgraded.
> ==> ERROR: Failed to install packages to new root

**Comment by bill88t** [comment]
Oh my key wasn't in the readme.
I added it under [BredOS gpg keys](https://github.com/BredOS/images#building-specific-images) and published to the keyservers so it can be fetched.
Rerun the command and everything will work now.
